version: '2'
services:
  consul:
    image: "consul:latest"
    ports:
      - "53/udp:53/udp"
      - "8301/udp:8301/udp"
      - "8500:8500"
    command: "agent -server -bootstrap-expect=1 -ui -client=0.0.0.0"
  registrator:
    image: "gliderlabs/registrator:latest"
    volumes:
      - /var/run/docker.sock:/var/tmp/docker.sock
    environment:
      DOCKER_HOST: "unix:///var/tmp/docker.sock"
    command: "-internal consul://consul:8500"
    dns:
      - ${DOCKER_MACHINE_IP}
    dns_search:
      - service.consul
      - node.consul
    depends_on:
      - consul
  consul-template:
    image: "camilocot/docker-image-consul-template:latest"
    environment:
      CONTAINER: "graylogdocker_haproxy_1"
    command: "-consul consul:8500 -log-level debug -template /tmp/haproxy.ctmpl:/tmp/haproxy.cfg:/send-container-signal.sh"
    volumes:
      - /tmp/haproxy:/tmp
      - /var/run/docker.sock:/var/run/docker.sock
    dns:
      - ${DOCKER_MACHINE_IP}
    dns_search:
      - service.consul
      - node.consul
    depends_on:
      - consul
  haproxy:
    image: camilocot/haproxy-wait-for-file
    volumes:
      - /tmp/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - consul-template
      - graylog-server
    ports:
      - "9000:9000"
      - "12900:12900"
      - "1936:1936"
    entrypoint: /wait-for-file.sh /usr/local/etc/haproxy/haproxy.cfg haproxy -f /usr/local/etc/haproxy/haproxy.cfg
  mongo:
    image: "mongo:3"
    volumes:
      - /graylog/data/mongo:/data/db
    dns:
      - ${DOCKER_MACHINE_IP}
    dns_search:
      - service.consul
      - node.consul
    depends_on:
      - consul
  elasticsearch:
    image: "elasticsearch:2"
    command: "elasticsearch -Des.cluster.name='graylog'"
    volumes:
      - /graylog/data/elasticsearch:/usr/share/elasticsearch/data
    dns:
      - ${DOCKER_MACHINE_IP}
    dns_search:
      - service.consul
      - node.consul
    depends_on:
      - consul
  graylog-server:
    image: graylog2/server
    volumes:
      - /tmp/graylog/graylog.conf:/usr/share/graylog/data/config/graylog.conf
    depends_on:
      - mongo
      - elasticsearch
